# Generated by Django 3.2.7 on 2021-09-20 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_subtitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtitle',
            old_name='Subtitle',
            new_name='subtitle',
        ),
    ]
