# Generated by Django 3.2.7 on 2021-09-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_subtitle_subtitle_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cation', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='imag/%y')),
            ],
        ),
    ]
