# Generated by Django 3.2.7 on 2021-09-21 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='cation',
            new_name='caption',
        ),
    ]
