# Generated by Django 3.2.7 on 2021-09-21 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_banner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Logo',
        ),
    ]
