# Generated by Django 3.2.7 on 2021-09-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_nav_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='imag/%y')),
            ],
        ),
    ]
