# Generated by Django 3.2.7 on 2021-09-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_footer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='imag/%y')),
            ],
        ),
    ]
