# Generated by Django 3.2.7 on 2021-09-22 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_feature'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About_image',
        ),
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='imag/%y'),
        ),
    ]
