# Generated by Django 3.2.7 on 2021-09-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210922_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='caption',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
