# Generated by Django 3.2.7 on 2021-09-22 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_about_caption'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
