# Generated by Django 3.2.7 on 2021-09-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('designation', models.TextField(max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='imag/%y')),
                ('facebook', models.TextField(blank=True, max_length=50, null=True)),
                ('twitter', models.TextField(blank=True, max_length=50, null=True)),
                ('social3', models.TextField(blank=True, max_length=50, null=True)),
                ('social4', models.TextField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
