# Generated by Django 3.2.7 on 2021-09-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_team2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clint_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clint_pic', models.ImageField(blank=True, null=True, upload_to='imag/%y')),
                ('comment', models.TextField(max_length=1000)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
