# Generated by Django 3.2.7 on 2021-09-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_clint_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=50, null=True)),
                ('details', models.TextField(max_length=1000)),
                ('address1', models.TextField(max_length=200)),
                ('address2', models.TextField(max_length=200)),
                ('phNumber1', models.TextField(max_length=100)),
                ('phNumber2', models.TextField(max_length=100)),
                ('facebook', models.TextField(blank=True, max_length=50, null=True)),
                ('twitter', models.TextField(blank=True, max_length=50, null=True)),
                ('social3', models.TextField(blank=True, max_length=50, null=True)),
                ('social4', models.TextField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
